export const CATEGORIES = [
  'هەموو',
  'سەرەتا',
  'نووسین',
  'وێنە',
  'داتا',
  'کۆتایی',
];

export const LAYOUTS = [
  // --- سەرەتا (Start) ---
  {
    key: 'title',
    category: 'سەرەتا',
    title: 'سەردێڕی سەرەکی',
    desc: 'سەردێڕی سەرەکی و ژێرنووس بۆ پەڕەی دەستپێک',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 28,
        width: 90,
        height: 25,
        zIndex: 1,
        text: 'سەردێڕی سەرەکی پاوەرپۆینت',
        fontMode: 'auto',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textDecorationLine: 'none',
        color: '#D24726',
        highlightColor: 'transparent',
        textAlign: 'center',
        writingDirection: 'rtl',
        lineSpacing: 1.2,
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'text',
        x: 10,
        y: 55,
        width: 80,
        height: 20,
        zIndex: 1,
        text: 'ژێرنووس یان کورتەی بابەتەکەت لێرە بنووسە',
        fontMode: 'auto',
        fontWeight: 'normal',
        fontStyle: 'italic',
        textDecorationLine: 'none',
        color: '#555555',
        highlightColor: 'transparent',
        textAlign: 'center',
        writingDirection: 'rtl',
        lineSpacing: 1.2,
      },
    ],
  },
  {
    key: 'section_header',
    category: 'سەرەتا',
    title: 'سەردێڕی بەش',
    desc: 'سەردێڕی سەرەکی بۆ جیاکردنەوەی بەشەکان',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 32,
        width: 90,
        height: 22,
        zIndex: 1,
        text: 'بەشی یەکەم: ناوی بەشەکە',
        fontMode: 'auto',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textDecorationLine: 'none',
        color: '#1c1c1e',
        highlightColor: 'transparent',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'text',
        x: 15,
        y: 58,
        width: 70,
        height: 18,
        zIndex: 1,
        text: 'وەسفێکی کورت سەبارەت بە تەوەرەکانی ئەم بەشە',
        fontMode: 'auto',
        fontWeight: 'normal',
        fontStyle: 'normal',
        textDecorationLine: 'none',
        color: '#666666',
        highlightColor: 'transparent',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
    ],
  },
  {
    key: 'agenda',
    category: 'سەرەتا',
    title: 'کارنامە (Agenda)',
    desc: 'لیستی تەوەرە سەرەکییەکانی پاوەرپۆینتەکە',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 8,
        width: 90,
        height: 16,
        zIndex: 1,
        text: 'کارنامەی پێشاندانی زانیارییەکان',
        fontMode: 'auto',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textDecorationLine: 'none',
        color: '#D24726',
        highlightColor: 'transparent',
        textAlign: 'right',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'text',
        x: 5,
        y: 28,
        width: 90,
        height: 62,
        zIndex: 1,
        text: '١. پێشەکی و کورتەی بابەت\n٢. خاڵە سەرەکییەکان و شیکاری\n٣. ئامار و داتاکان\n٤. ئەنجامگیری و کۆتایی',
        fontMode: 'auto',
        fontWeight: 'normal',
        fontStyle: 'normal',
        textDecorationLine: 'none',
        color: '#1c1c1e',
        highlightColor: 'transparent',
        textAlign: 'right',
        writingDirection: 'rtl',
        lineSpacing: 1.5,
      },
    ],
  },

  // --- نووسین (Text) ---
  {
    key: 'title_bullets',
    category: 'نووسین',
    title: 'سەردێڕ و خاڵبەندی',
    desc: 'سەردێڕ لەگەڵ لیستی خاڵەکان',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 8,
        width: 90,
        height: 16,
        zIndex: 1,
        text: 'سەردێڕی بابەتەکە',
        fontMode: 'auto',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textDecorationLine: 'none',
        color: '#1c1c1e',
        highlightColor: 'transparent',
        textAlign: 'right',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'text',
        x: 5,
        y: 28,
        width: 90,
        height: 62,
        zIndex: 1,
        text: '• خاڵی یەکەمی ڕوونکردنەوەی بابەتەکە\n• خاڵی دووەمی زانیارییەکان\n• لێرە دەتوانی دەقی تێروتەسەل یان زانیارییەکان بنووسی.',
        fontMode: 'auto',
        fontWeight: 'normal',
        fontStyle: 'normal',
        textDecorationLine: 'none',
        color: '#333333',
        highlightColor: 'transparent',
        textAlign: 'right',
        writingDirection: 'rtl',
        lineSpacing: 1.4,
      },
    ],
  },
  {
    key: 'two_columns',
    category: 'نووسین',
    title: 'دوو ستوون دەق',
    desc: 'دابەشکردنی دەق بەسەر دوو ستوونی تەریب',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 8,
        width: 90,
        height: 15,
        zIndex: 1,
        text: 'سەردێڕی سەرەکی دوو ستوونەکە',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#1c1c1e',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'text',
        x: 52,
        y: 28,
        width: 43,
        height: 62,
        zIndex: 1,
        text: 'ستوونی یەکەم:\n• ڕوونکردنەوەی لایەنی یەکەم\n• زانیاریی زۆرتر لێرە بنووسە',
        fontMode: 'auto',
        fontWeight: 'normal',
        color: '#333333',
        textAlign: 'right',
        writingDirection: 'rtl',
        lineSpacing: 1.3,
      },
      {
        id: `elem_${Date.now()}_3`,
        type: 'text',
        x: 5,
        y: 28,
        width: 43,
        height: 62,
        zIndex: 1,
        text: 'ستوونی دووەم:\n• ڕوونکردنەوەی لایەنی دووەم\n• خاڵە بەپێزەکانی ئەم تەوەرە',
        fontMode: 'auto',
        fontWeight: 'normal',
        color: '#333333',
        textAlign: 'right',
        writingDirection: 'rtl',
        lineSpacing: 1.3,
      },
    ],
  },
  {
    key: 'comparison',
    category: 'نووسین',
    title: 'بەراوردکاری (Comparison)',
    desc: 'بەراوردکردنی دوو بیرۆکە یان بابەت',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 6,
        width: 90,
        height: 14,
        zIndex: 1,
        text: 'بەراوردکردنی بژاردەکان',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#D24726',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'text',
        x: 52,
        y: 22,
        width: 43,
        height: 12,
        zIndex: 1,
        text: 'بژاردەی A (لایەنە باشەکان)',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#30d158',
        textAlign: 'right',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_3`,
        type: 'text',
        x: 52,
        y: 36,
        width: 43,
        height: 55,
        zIndex: 1,
        text: '• سەربەخۆیی بەرز\n• تێچووی کەمتر\n• جێبەجێکردنی خێرا',
        fontMode: 'auto',
        color: '#333333',
        textAlign: 'right',
        writingDirection: 'rtl',
        lineSpacing: 1.3,
      },
      {
        id: `elem_${Date.now()}_4`,
        type: 'text',
        x: 5,
        y: 22,
        width: 43,
        height: 12,
        zIndex: 1,
        text: 'بژاردەی B (کەمپووکتییەکان)',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#ff453a',
        textAlign: 'right',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_5`,
        type: 'text',
        x: 5,
        y: 36,
        width: 43,
        height: 55,
        zIndex: 1,
        text: '• پێویستی بە کاتی زیاتر\n• ئاڵۆزی لە بەڕێوەبردن\n• پێویستی بە تیمی گەورەتر',
        fontMode: 'auto',
        color: '#333333',
        textAlign: 'right',
        writingDirection: 'rtl',
        lineSpacing: 1.3,
      },
    ],
  },
  {
    key: 'quote',
    category: 'نووسین',
    title: 'وتەی بەنرخ (Quote)',
    desc: 'پیشاندانی وتە یان دەقێکی گرنگ بە شێوازی جوان',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 10,
        y: 25,
        width: 80,
        height: 38,
        zIndex: 1,
        text: '«زانست و زانیاری بەهێزترین چەکین کە دەتوانیت بەکاریان بهێنیت بۆ گۆڕینی جیهان.»',
        fontMode: 'auto',
        fontWeight: 'bold',
        fontStyle: 'italic',
        color: '#1c1c1e',
        textAlign: 'center',
        writingDirection: 'rtl',
        lineSpacing: 1.4,
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'text',
        x: 20,
        y: 68,
        width: 60,
        height: 15,
        zIndex: 1,
        text: '— ناوی خاوەنی وتەکە / سەرچاوە',
        fontMode: 'auto',
        fontWeight: 'normal',
        color: '#D24726',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
    ],
  },
  {
    key: 'big_statement',
    category: 'نووسین',
    title: 'پەیامی گەورە (Big Statement)',
    desc: 'دەقێکی زۆر گەورە بۆ ڕاکێشانی سەرنجی ئامادەبووان',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 28,
        width: 90,
        height: 48,
        zIndex: 1,
        text: 'سەرکەوتن بەرهەمی هەوڵدانی بەردەوامە، نهێنییەکی نادیار نییە!',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#D24726',
        textAlign: 'center',
        writingDirection: 'rtl',
        lineSpacing: 1.3,
      },
    ],
  },

  // --- وێنە (Images) ---
  {
    key: 'image_right_text',
    category: 'وێنە',
    title: 'وێنە لە ڕاست + دەق',
    desc: 'وێنە لە دەستی ڕاست و دەق لە دەستی چەپ',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 6,
        width: 90,
        height: 14,
        zIndex: 1,
        text: 'سەردێڕی بابەتەکە',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#1c1c1e',
        textAlign: 'right',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'image',
        x: 52,
        y: 22,
        width: 43,
        height: 70,
        zIndex: 1,
        uri: null,
      },
      {
        id: `elem_${Date.now()}_3`,
        type: 'text',
        x: 5,
        y: 22,
        width: 43,
        height: 70,
        zIndex: 1,
        text: '• وەسف و شیکردنەوەی پەیوەندیدار بە وێنەکەوە\n• نووسینی شیکاری و خاڵە گرنگەکان.',
        fontMode: 'auto',
        color: '#333333',
        textAlign: 'right',
        writingDirection: 'rtl',
        lineSpacing: 1.3,
      },
    ],
  },
  {
    key: 'image_left_text',
    category: 'وێنە',
    title: 'وێنە لە چەپ + دەق',
    desc: 'وێنە لە دەستی چەپ و دەق لە دەستی ڕاست',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 6,
        width: 90,
        height: 14,
        zIndex: 1,
        text: 'سەردێڕی بابەتەکە',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#1c1c1e',
        textAlign: 'right',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'text',
        x: 52,
        y: 22,
        width: 43,
        height: 70,
        zIndex: 1,
        text: '• وەسف و ڕوونکردنەوەی زانیارییەکان\n• خاڵی سەرەکی سەبارەت بە بابەتەکە.',
        fontMode: 'auto',
        color: '#333333',
        textAlign: 'right',
        writingDirection: 'rtl',
        lineSpacing: 1.3,
      },
      {
        id: `elem_${Date.now()}_3`,
        type: 'image',
        x: 5,
        y: 22,
        width: 43,
        height: 70,
        zIndex: 1,
        uri: null,
      },
    ],
  },
  {
    key: 'full_image_caption',
    category: 'وێنە',
    title: 'وێنەی سەرانسەری + وەسف',
    desc: 'وێنەیەکی گەورە لەگەڵ نووسین لە خوارەوە',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'image',
        x: 5,
        y: 5,
        width: 90,
        height: 72,
        zIndex: 1,
        uri: null,
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'text',
        x: 5,
        y: 80,
        width: 90,
        height: 15,
        zIndex: 1,
        text: 'ژێرنووس و ڕوونکردنەوەی وێنەی سەرەوە لێرە دەنووسرێت',
        fontMode: 'auto',
        fontStyle: 'italic',
        color: '#555555',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
    ],
  },
  {
    key: 'image_grid_2',
    category: 'وێنە',
    title: 'دوو وێنە (Grid of 2)',
    desc: 'دوو وێنەی تەریب لە تەنیشت یەکتر',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 5,
        width: 90,
        height: 12,
        zIndex: 1,
        text: 'بەراوردکردنی دوو وێنە',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#1c1c1e',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'image',
        x: 52,
        y: 20,
        width: 43,
        height: 72,
        zIndex: 1,
        uri: null,
      },
      {
        id: `elem_${Date.now()}_3`,
        type: 'image',
        x: 5,
        y: 20,
        width: 43,
        height: 72,
        zIndex: 1,
        uri: null,
      },
    ],
  },
  {
    key: 'image_grid_3',
    category: 'وێنە',
    title: 'سێ وێنە (Grid of 3)',
    desc: 'سێ وێنە لە تەنیشت یەکتر',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 5,
        width: 90,
        height: 12,
        zIndex: 1,
        text: 'مۆلەقەی سێ وێنە',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#1c1c1e',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'image',
        x: 68,
        y: 20,
        width: 27,
        height: 72,
        zIndex: 1,
        uri: null,
      },
      {
        id: `elem_${Date.now()}_3`,
        type: 'image',
        x: 36,
        y: 20,
        width: 27,
        height: 72,
        zIndex: 1,
        uri: null,
      },
      {
        id: `elem_${Date.now()}_4`,
        type: 'image',
        x: 5,
        y: 20,
        width: 27,
        height: 72,
        zIndex: 1,
        uri: null,
      },
    ],
  },
  {
    key: 'image_grid_4',
    category: 'وێنە',
    title: 'چوار وێنە (Grid of 4)',
    desc: 'چوار وێنە بەشێوەی تۆڕی 2x2',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 4,
        width: 90,
        height: 10,
        zIndex: 1,
        text: 'گالێری چوار وێنە',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#1c1c1e',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'image',
        x: 52,
        y: 16,
        width: 43,
        height: 38,
        zIndex: 1,
        uri: null,
      },
      {
        id: `elem_${Date.now()}_3`,
        type: 'image',
        x: 5,
        y: 16,
        width: 43,
        height: 38,
        zIndex: 1,
        uri: null,
      },
      {
        id: `elem_${Date.now()}_4`,
        type: 'image',
        x: 52,
        y: 57,
        width: 43,
        height: 38,
        zIndex: 1,
        uri: null,
      },
      {
        id: `elem_${Date.now()}_5`,
        type: 'image',
        x: 5,
        y: 57,
        width: 43,
        height: 38,
        zIndex: 1,
        uri: null,
      },
    ],
  },
  {
    key: 'image_caption_below',
    category: 'وێنە',
    title: 'وێنە و وەصف لە خوارەوە',
    desc: 'سەردێڕ + وێنە لە سەرەوە + وەصف لە خوارەوە',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 5,
        width: 90,
        height: 12,
        zIndex: 1,
        text: 'سەردێڕی وێنەکە',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#1c1c1e',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'image',
        x: 10,
        y: 20,
        width: 80,
        height: 52,
        zIndex: 1,
        uri: null,
      },
      {
        id: `elem_${Date.now()}_3`,
        type: 'text',
        x: 5,
        y: 75,
        width: 90,
        height: 20,
        zIndex: 1,
        text: 'تەواوی ناواخنی نووسین یان شیکاری بۆ ئەم وێنەیە لەم بەشەدا دەستکاری بکە.',
        fontMode: 'auto',
        color: '#333333',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
    ],
  },

  // --- داتا (Data) ---
  {
    key: 'big_numbers',
    category: 'داتا',
    title: 'ژمارەی گەورە (Big Numbers)',
    desc: 'پیشاندانی 3 ئاماری سەرەکی و بەرچاو',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 6,
        width: 90,
        height: 12,
        zIndex: 1,
        text: 'دەستکەوت و ئامارەکان',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#D24726',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'text',
        x: 68,
        y: 28,
        width: 27,
        height: 22,
        zIndex: 1,
        text: '85%',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#30d158',
        textAlign: 'center',
        writingDirection: 'ltr',
      },
      {
        id: `elem_${Date.now()}_3`,
        type: 'text',
        x: 68,
        y: 52,
        width: 27,
        height: 35,
        zIndex: 1,
        text: 'ڕێژەی ڕەزامەندی بەکارهێنەران',
        fontMode: 'auto',
        color: '#444444',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_4`,
        type: 'text',
        x: 36,
        y: 28,
        width: 27,
        height: 22,
        zIndex: 1,
        text: '+50',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#007AFF',
        textAlign: 'center',
        writingDirection: 'ltr',
      },
      {
        id: `elem_${Date.now()}_5`,
        type: 'text',
        x: 36,
        y: 52,
        width: 27,
        height: 35,
        zIndex: 1,
        text: 'پڕۆژەی ئەنجامدراو',
        fontMode: 'auto',
        color: '#444444',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_6`,
        type: 'text',
        x: 5,
        y: 28,
        width: 27,
        height: 22,
        zIndex: 1,
        text: '100K',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#af52de',
        textAlign: 'center',
        writingDirection: 'ltr',
      },
      {
        id: `elem_${Date.now()}_7`,
        type: 'text',
        x: 5,
        y: 52,
        width: 27,
        height: 35,
        zIndex: 1,
        text: 'دابەزاندنی چالاک',
        fontMode: 'auto',
        color: '#444444',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
    ],
  },
  {
    key: 'timeline',
    category: 'داتا',
    title: 'هێڵی کات (Timeline)',
    desc: '4 هەنگاوی زنجیرەیی بەپێی کات',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 6,
        width: 90,
        height: 12,
        zIndex: 1,
        text: 'هێڵی کاتی پڕۆژەکە',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#1c1c1e',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'text',
        x: 74,
        y: 25,
        width: 21,
        height: 14,
        zIndex: 1,
        text: 'قۆناغی ١',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#D24726',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_3`,
        type: 'text',
        x: 74,
        y: 42,
        width: 21,
        height: 48,
        zIndex: 1,
        text: 'پلان دانان و توێژینەوەی سەرەتایی',
        fontMode: 'auto',
        color: '#444',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_4`,
        type: 'text',
        x: 51,
        y: 25,
        width: 21,
        height: 14,
        zIndex: 1,
        text: 'قۆناغی ٢',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#007AFF',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_5`,
        type: 'text',
        x: 51,
        y: 42,
        width: 21,
        height: 48,
        zIndex: 1,
        text: 'دیزاین و دروستکردنی نموونەی سەرەتایی',
        fontMode: 'auto',
        color: '#444',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_6`,
        type: 'text',
        x: 28,
        y: 25,
        width: 21,
        height: 14,
        zIndex: 1,
        text: 'قۆناغی ٣',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#ff9500',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_7`,
        type: 'text',
        x: 28,
        y: 42,
        width: 21,
        height: 48,
        zIndex: 1,
        text: 'تاقیکردنەوە و باشترکردن',
        fontMode: 'auto',
        color: '#444',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_8`,
        type: 'text',
        x: 5,
        y: 25,
        width: 21,
        height: 14,
        zIndex: 1,
        text: 'قۆناغی ٤',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#30d158',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_9`,
        type: 'text',
        x: 5,
        y: 42,
        width: 21,
        height: 48,
        zIndex: 1,
        text: 'ڕاگەیاندن و کارپێکردنی کۆتایی',
        fontMode: 'auto',
        color: '#444',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
    ],
  },
  {
    key: 'process',
    category: 'داتا',
    title: 'پرۆسە (Process)',
    desc: '3 هەنگاوی زنجیرەیی بە فلاش یان ڕیزبەند',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 6,
        width: 90,
        height: 12,
        zIndex: 1,
        text: 'پرۆسەی جێبەجێکردن',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#1c1c1e',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'text',
        x: 68,
        y: 25,
        width: 27,
        height: 60,
        zIndex: 1,
        text: '١. وەرگرتن\n\nتۆمارکردن و کۆکردنەوەی زانیاری سەرەتایی',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#ffffff',
        highlightColor: '#D24726',
        textAlign: 'center',
        writingDirection: 'rtl',
        lineSpacing: 1.3,
      },
      {
        id: `elem_${Date.now()}_3`,
        type: 'text',
        x: 36,
        y: 25,
        width: 27,
        height: 60,
        zIndex: 1,
        text: '٢. دەستکاری\n\nدارشتن و شیکردنەوەی خێرا',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#ffffff',
        highlightColor: '#007AFF',
        textAlign: 'center',
        writingDirection: 'rtl',
        lineSpacing: 1.3,
      },
      {
        id: `elem_${Date.now()}_4`,
        type: 'text',
        x: 5,
        y: 25,
        width: 27,
        height: 60,
        zIndex: 1,
        text: '٣. ناردن\n\nڕادەستکردنی بەرهەمی کۆتایی',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#ffffff',
        highlightColor: '#30d158',
        textAlign: 'center',
        writingDirection: 'rtl',
        lineSpacing: 1.3,
      },
    ],
  },
  {
    key: 'table',
    category: 'داتا',
    title: 'خشتەی زانیاری (Table)',
    desc: 'ڕێکخستنی زانیاری لە شێوەی خشتە',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 6,
        width: 90,
        height: 12,
        zIndex: 1,
        text: 'خشتەی زانیاری و بەراوردکاری',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#1c1c1e',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'text',
        isTable: true,
        x: 5,
        y: 22,
        width: 90,
        height: 14,
        zIndex: 1,
        text: 'ناوی بابەت  |  بڕ / بڕیار  |  باری تەندروستی  |  تێبینی',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#ffffff',
        highlightColor: '#D24726',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_3`,
        type: 'text',
        isTable: true,
        x: 5,
        y: 38,
        width: 90,
        height: 52,
        zIndex: 1,
        text: 'پڕۆژەی A  |  $12,000  |  تەواوبوو  |  سەرکەوتوو\n---------------------------------------------\nپڕۆژەی B  |  $8,500  |  لە ئیشدایە  |  لەکاتدا\n---------------------------------------------\nپڕۆژەی C  |  $15,000  |  چاوەڕوانکراو  |  پلانی نوێ',
        fontMode: 'auto',
        color: '#333333',
        textAlign: 'center',
        writingDirection: 'rtl',
        lineSpacing: 1.3,
      },
    ],
  },

  // --- کۆتایی (Ending) ---
  {
    key: 'thank_you',
    category: 'کۆتایی',
    title: 'سوپاس و پەیوەندی',
    desc: 'پەڕەی کۆتایی و زانیاری پەیوەندیکردن',
    createElements: () => [
      {
        id: `elem_${Date.now()}_1`,
        type: 'text',
        x: 5,
        y: 22,
        width: 90,
        height: 25,
        zIndex: 1,
        text: 'سوپاس بۆ سەرنج و کاتتان! 🙏',
        fontMode: 'auto',
        fontWeight: 'bold',
        color: '#D24726',
        textAlign: 'center',
        writingDirection: 'rtl',
      },
      {
        id: `elem_${Date.now()}_2`,
        type: 'text',
        x: 10,
        y: 52,
        width: 80,
        height: 32,
        zIndex: 1,
        text: '📧 ئیمەیڵ: info@example.com\n📞 مۆبایل: 0750 000 0000\n🌐 وێبسایت: www.example.com',
        fontMode: 'auto',
        color: '#444444',
        textAlign: 'center',
        writingDirection: 'rtl',
        lineSpacing: 1.4,
      },
    ],
  },
  {
    key: 'blank',
    category: 'کۆتایی',
    title: 'بەتاڵ (Blank)',
    desc: 'سڵایدێکی سپی و بەتاڵ بەبێ هیچ بەشێک',
    createElements: () => [],
  },
];
